export const allText = {
  header: {
    fontFamily: 'Raleway',
    fontSize: 45,
    color: '#F9DF99',
    fontWeight: '500',
    marginLeft: 15,
    marginTop: 20,
    marginBottom: 20,
  },
  text: {
    fontFamily: 'Raleway',
    fontSize: 20,
    color: '#F9DF99',
    marginTop: 20,
    marginLeft: 10,
  },
  titleLine: {
    backgroundColor: '#F9DF99',
    height: 2,
    width: 90,
  },
  titleContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  titleImageBackground: {
    height: 200,
  },
  linearGradient: {
    flex: 1,
    height: 100,
  },
  dropDown: {
    fontFamily: 'Raleway',
    fontSize: 20,
    marginLeft: 10,
    color: '#F9DF99',
    textAlign: 'right',
  },
  dropDownRow: {
    fontFamily: 'Raleway',
    fontSize: 20,
    marginLeft: 10,
    color: '#F9DF99',
    textAlign: 'center',
  },
};

export const infoText: any = {
  header: {
    fontFamily: 'Raleway',
    fontSize: 45,
    color: '#F9DF99',
    fontWeight: '500',
    marginRight: 'auto',
    marginLeft: 20,
    marginTop: 20,
    marginBottom: 20,
  },
  subHeading: {
    fontFamily: 'Raleway',
    fontSize: 25,
    color: '#F9DF99',
    fontWeight: '500',
  },
  subHeading2: {
    fontFamily: 'Raleway',
    fontSize: 20,
    marginLeft: 15,
    color: '#F9DF99',
    fontWeight: '500',
  },
  main: {
    fontFamily: 'Raleway',
    fontSize: 20,
    color: '#F9DF99',
    fontWeight: '300',
    marginRight: 30,
    marginLeft: 20,
    marginTop: 20,
    marginBottom: 20,
  },
  locationText: {
    fontFamily: 'Raleway',
    fontSize: 20,
    color: '#F9DF99',
    fontWeight: '300',
    marginRight: 5,
    marginBottom: 5,
    marginTop: 20,
  },
  list: {
    fontFamily: 'Raleway',
    fontSize: 20,
    color: '#F9DF99',
    fontWeight: '300',
    marginRight: 30,
    marginLeft: 20,
    marginTop: 5,
  },
};
